// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVA_Registro_de_Vacunados.Data;

namespace TVA_Registro_de_Vacunados.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220120211536_Initialcreate")]
    partial class Initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("TVA_Registro_de_Vacunados.Models.Trabajador", b =>
                {
                    b.Property<int>("IdTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidosTrabajador")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarneITrabajador")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartamentoTrabajador")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdadTrabajador")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreTrabajador")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTrabajador");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("TVA_Registro_de_Vacunados.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoUsuario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreadoUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TVA_Registro_de_Vacunados.Models.Vacuna", b =>
                {
                    b.Property<int>("IdVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DosisVacuna")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaVacuna")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoteVacuna")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreVacuna")
                        .HasColumnType("TEXT");

                    b.HasKey("IdVacuna");

                    b.ToTable("Vacunas");
                });
#pragma warning restore 612, 618
        }
    }
}
